/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProofOfReservesRouteImport } from './routes/proof-of-reserves'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as JewelryRouteImport } from './routes/jewelry'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AmlPolicyRouteImport } from './routes/aml-policy'
import { Route as AmlComplianceRouteImport } from './routes/aml-compliance'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppWalletRouteImport } from './routes/app.wallet'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppKycRouteImport } from './routes/app.kyc'
import { Route as AppJewelryOrdersRouteImport } from './routes/app.jewelry-orders'
import { Route as AppInvestRouteImport } from './routes/app.invest'
import { Route as AppHoldingsRouteImport } from './routes/app.holdings'
import { Route as AppCryptoRouteImport } from './routes/app.crypto'
import { Route as AppCheckoutRouteImport } from './routes/app.checkout'
import { Route as AppCertificatesRouteImport } from './routes/app.certificates'
import { Route as AppCartRouteImport } from './routes/app.cart'
import { Route as AppCardRouteImport } from './routes/app.card'
import { Route as AppBuyRouteImport } from './routes/app.buy'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AdminWaitlistRouteImport } from './routes/admin.waitlist'
import { Route as AdminVaultsRouteImport } from './routes/admin.vaults'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSystemHealthRouteImport } from './routes/admin.system-health'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSeedExportsRouteImport } from './routes/admin.seed-exports'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMarketplaceRouteImport } from './routes/admin.marketplace'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AdminJewelryOrdersRouteImport } from './routes/admin.jewelry-orders'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminCryptoRouteImport } from './routes/admin.crypto'
import { Route as AdminCouriersRouteImport } from './routes/admin.couriers'
import { Route as AdminConfigsRouteImport } from './routes/admin.configs'
import { Route as AdminConfigVersionsRouteImport } from './routes/admin.config-versions'
import { Route as AdminConfigBackupsRouteImport } from './routes/admin.config-backups'
import { Route as AdminAuditsRouteImport } from './routes/admin.audits'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AppMarketplaceIndexRouteImport } from './routes/app.marketplace.index'
import { Route as AppMarketplaceSlugRouteImport } from './routes/app.marketplace.$slug'
import { Route as AppJewelryOrdersIdRouteImport } from './routes/app.jewelry-orders.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofOfReservesRoute = ProofOfReservesRouteImport.update({
  id: '/proof-of-reserves',
  path: '/proof-of-reserves',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelryRoute = JewelryRouteImport.update({
  id: '/jewelry',
  path: '/jewelry',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AmlPolicyRoute = AmlPolicyRouteImport.update({
  id: '/aml-policy',
  path: '/aml-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AmlComplianceRoute = AmlComplianceRouteImport.update({
  id: '/aml-compliance',
  path: '/aml-compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppKycRoute = AppKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AppRoute,
} as any)
const AppJewelryOrdersRoute = AppJewelryOrdersRouteImport.update({
  id: '/jewelry-orders',
  path: '/jewelry-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestRoute = AppInvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => AppRoute,
} as any)
const AppHoldingsRoute = AppHoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => AppRoute,
} as any)
const AppCryptoRoute = AppCryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesRoute = AppCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppRoute,
} as any)
const AppCardRoute = AppCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyRoute = AppBuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AdminWaitlistRoute = AdminWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVaultsRoute = AdminVaultsRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemHealthRoute = AdminSystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeedExportsRoute = AdminSeedExportsRouteImport.update({
  id: '/seed-exports',
  path: '/seed-exports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketplaceRoute = AdminMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJewelryOrdersRoute = AdminJewelryOrdersRouteImport.update({
  id: '/jewelry-orders',
  path: '/jewelry-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCryptoRoute = AdminCryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouriersRoute = AdminCouriersRouteImport.update({
  id: '/couriers',
  path: '/couriers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigsRoute = AdminConfigsRouteImport.update({
  id: '/configs',
  path: '/configs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigVersionsRoute = AdminConfigVersionsRouteImport.update({
  id: '/config-versions',
  path: '/config-versions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigBackupsRoute = AdminConfigBackupsRouteImport.update({
  id: '/config-backups',
  path: '/config-backups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditsRoute = AdminAuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AppMarketplaceIndexRoute = AppMarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceSlugRoute = AppMarketplaceSlugRouteImport.update({
  id: '/marketplace/$slug',
  path: '/marketplace/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppJewelryOrdersIdRoute = AppJewelryOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppJewelryOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/aml-compliance': typeof AmlComplianceRoute
  '/aml-policy': typeof AmlPolicyRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/insurance': typeof InsuranceRoute
  '/invest': typeof InvestRoute
  '/jewelry': typeof JewelryRoute
  '/privacy': typeof PrivacyRoute
  '/proof-of-reserves': typeof ProofOfReservesRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audits': typeof AdminAuditsRoute
  '/admin/config-backups': typeof AdminConfigBackupsRoute
  '/admin/config-versions': typeof AdminConfigVersionsRoute
  '/admin/configs': typeof AdminConfigsRoute
  '/admin/couriers': typeof AdminCouriersRoute
  '/admin/crypto': typeof AdminCryptoRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/jewelry-orders': typeof AdminJewelryOrdersRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/seed-exports': typeof AdminSeedExportsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vaults': typeof AdminVaultsRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/buy': typeof AppBuyRoute
  '/app/card': typeof AppCardRoute
  '/app/cart': typeof AppCartRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/crypto': typeof AppCryptoRoute
  '/app/holdings': typeof AppHoldingsRoute
  '/app/invest': typeof AppInvestRoute
  '/app/jewelry-orders': typeof AppJewelryOrdersRouteWithChildren
  '/app/kyc': typeof AppKycRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/support': typeof AppSupportRoute
  '/app/wallet': typeof AppWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/jewelry-orders/$id': typeof AppJewelryOrdersIdRoute
  '/app/marketplace/$slug': typeof AppMarketplaceSlugRoute
  '/app/marketplace/': typeof AppMarketplaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aml-compliance': typeof AmlComplianceRoute
  '/aml-policy': typeof AmlPolicyRoute
  '/auth': typeof AuthRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/insurance': typeof InsuranceRoute
  '/invest': typeof InvestRoute
  '/jewelry': typeof JewelryRoute
  '/privacy': typeof PrivacyRoute
  '/proof-of-reserves': typeof ProofOfReservesRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audits': typeof AdminAuditsRoute
  '/admin/config-backups': typeof AdminConfigBackupsRoute
  '/admin/config-versions': typeof AdminConfigVersionsRoute
  '/admin/configs': typeof AdminConfigsRoute
  '/admin/couriers': typeof AdminCouriersRoute
  '/admin/crypto': typeof AdminCryptoRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/jewelry-orders': typeof AdminJewelryOrdersRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/seed-exports': typeof AdminSeedExportsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vaults': typeof AdminVaultsRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/buy': typeof AppBuyRoute
  '/app/card': typeof AppCardRoute
  '/app/cart': typeof AppCartRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/crypto': typeof AppCryptoRoute
  '/app/holdings': typeof AppHoldingsRoute
  '/app/invest': typeof AppInvestRoute
  '/app/jewelry-orders': typeof AppJewelryOrdersRouteWithChildren
  '/app/kyc': typeof AppKycRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/support': typeof AppSupportRoute
  '/app/wallet': typeof AppWalletRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/app/jewelry-orders/$id': typeof AppJewelryOrdersIdRoute
  '/app/marketplace/$slug': typeof AppMarketplaceSlugRoute
  '/app/marketplace': typeof AppMarketplaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/aml-compliance': typeof AmlComplianceRoute
  '/aml-policy': typeof AmlPolicyRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/insurance': typeof InsuranceRoute
  '/invest': typeof InvestRoute
  '/jewelry': typeof JewelryRoute
  '/privacy': typeof PrivacyRoute
  '/proof-of-reserves': typeof ProofOfReservesRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audits': typeof AdminAuditsRoute
  '/admin/config-backups': typeof AdminConfigBackupsRoute
  '/admin/config-versions': typeof AdminConfigVersionsRoute
  '/admin/configs': typeof AdminConfigsRoute
  '/admin/couriers': typeof AdminCouriersRoute
  '/admin/crypto': typeof AdminCryptoRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/jewelry-orders': typeof AdminJewelryOrdersRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/seed-exports': typeof AdminSeedExportsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vaults': typeof AdminVaultsRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/buy': typeof AppBuyRoute
  '/app/card': typeof AppCardRoute
  '/app/cart': typeof AppCartRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/crypto': typeof AppCryptoRoute
  '/app/holdings': typeof AppHoldingsRoute
  '/app/invest': typeof AppInvestRoute
  '/app/jewelry-orders': typeof AppJewelryOrdersRouteWithChildren
  '/app/kyc': typeof AppKycRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/support': typeof AppSupportRoute
  '/app/wallet': typeof AppWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/jewelry-orders/$id': typeof AppJewelryOrdersIdRoute
  '/app/marketplace/$slug': typeof AppMarketplaceSlugRoute
  '/app/marketplace/': typeof AppMarketplaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/aml-compliance'
    | '/aml-policy'
    | '/app'
    | '/auth'
    | '/buy'
    | '/contact'
    | '/insurance'
    | '/invest'
    | '/jewelry'
    | '/privacy'
    | '/proof-of-reserves'
    | '/terms'
    | '/admin/analytics'
    | '/admin/audits'
    | '/admin/config-backups'
    | '/admin/config-versions'
    | '/admin/configs'
    | '/admin/couriers'
    | '/admin/crypto'
    | '/admin/faqs'
    | '/admin/jewelry-orders'
    | '/admin/kyc'
    | '/admin/marketplace'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/providers'
    | '/admin/seed-exports'
    | '/admin/support'
    | '/admin/system-health'
    | '/admin/users'
    | '/admin/vaults'
    | '/admin/waitlist'
    | '/app/alerts'
    | '/app/buy'
    | '/app/card'
    | '/app/cart'
    | '/app/certificates'
    | '/app/checkout'
    | '/app/crypto'
    | '/app/holdings'
    | '/app/invest'
    | '/app/jewelry-orders'
    | '/app/kyc'
    | '/app/notifications'
    | '/app/orders'
    | '/app/profile'
    | '/app/support'
    | '/app/wallet'
    | '/admin/'
    | '/app/'
    | '/app/jewelry-orders/$id'
    | '/app/marketplace/$slug'
    | '/app/marketplace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/aml-compliance'
    | '/aml-policy'
    | '/auth'
    | '/buy'
    | '/contact'
    | '/insurance'
    | '/invest'
    | '/jewelry'
    | '/privacy'
    | '/proof-of-reserves'
    | '/terms'
    | '/admin/analytics'
    | '/admin/audits'
    | '/admin/config-backups'
    | '/admin/config-versions'
    | '/admin/configs'
    | '/admin/couriers'
    | '/admin/crypto'
    | '/admin/faqs'
    | '/admin/jewelry-orders'
    | '/admin/kyc'
    | '/admin/marketplace'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/providers'
    | '/admin/seed-exports'
    | '/admin/support'
    | '/admin/system-health'
    | '/admin/users'
    | '/admin/vaults'
    | '/admin/waitlist'
    | '/app/alerts'
    | '/app/buy'
    | '/app/card'
    | '/app/cart'
    | '/app/certificates'
    | '/app/checkout'
    | '/app/crypto'
    | '/app/holdings'
    | '/app/invest'
    | '/app/jewelry-orders'
    | '/app/kyc'
    | '/app/notifications'
    | '/app/orders'
    | '/app/profile'
    | '/app/support'
    | '/app/wallet'
    | '/admin'
    | '/app'
    | '/app/jewelry-orders/$id'
    | '/app/marketplace/$slug'
    | '/app/marketplace'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/aml-compliance'
    | '/aml-policy'
    | '/app'
    | '/auth'
    | '/buy'
    | '/contact'
    | '/insurance'
    | '/invest'
    | '/jewelry'
    | '/privacy'
    | '/proof-of-reserves'
    | '/terms'
    | '/admin/analytics'
    | '/admin/audits'
    | '/admin/config-backups'
    | '/admin/config-versions'
    | '/admin/configs'
    | '/admin/couriers'
    | '/admin/crypto'
    | '/admin/faqs'
    | '/admin/jewelry-orders'
    | '/admin/kyc'
    | '/admin/marketplace'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/providers'
    | '/admin/seed-exports'
    | '/admin/support'
    | '/admin/system-health'
    | '/admin/users'
    | '/admin/vaults'
    | '/admin/waitlist'
    | '/app/alerts'
    | '/app/buy'
    | '/app/card'
    | '/app/cart'
    | '/app/certificates'
    | '/app/checkout'
    | '/app/crypto'
    | '/app/holdings'
    | '/app/invest'
    | '/app/jewelry-orders'
    | '/app/kyc'
    | '/app/notifications'
    | '/app/orders'
    | '/app/profile'
    | '/app/support'
    | '/app/wallet'
    | '/admin/'
    | '/app/'
    | '/app/jewelry-orders/$id'
    | '/app/marketplace/$slug'
    | '/app/marketplace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AmlComplianceRoute: typeof AmlComplianceRoute
  AmlPolicyRoute: typeof AmlPolicyRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  BuyRoute: typeof BuyRoute
  ContactRoute: typeof ContactRoute
  InsuranceRoute: typeof InsuranceRoute
  InvestRoute: typeof InvestRoute
  JewelryRoute: typeof JewelryRoute
  PrivacyRoute: typeof PrivacyRoute
  ProofOfReservesRoute: typeof ProofOfReservesRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof-of-reserves': {
      id: '/proof-of-reserves'
      path: '/proof-of-reserves'
      fullPath: '/proof-of-reserves'
      preLoaderRoute: typeof ProofOfReservesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewelry': {
      id: '/jewelry'
      path: '/jewelry'
      fullPath: '/jewelry'
      preLoaderRoute: typeof JewelryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aml-policy': {
      id: '/aml-policy'
      path: '/aml-policy'
      fullPath: '/aml-policy'
      preLoaderRoute: typeof AmlPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aml-compliance': {
      id: '/aml-compliance'
      path: '/aml-compliance'
      fullPath: '/aml-compliance'
      preLoaderRoute: typeof AmlComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kyc': {
      id: '/app/kyc'
      path: '/kyc'
      fullPath: '/app/kyc'
      preLoaderRoute: typeof AppKycRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jewelry-orders': {
      id: '/app/jewelry-orders'
      path: '/jewelry-orders'
      fullPath: '/app/jewelry-orders'
      preLoaderRoute: typeof AppJewelryOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invest': {
      id: '/app/invest'
      path: '/invest'
      fullPath: '/app/invest'
      preLoaderRoute: typeof AppInvestRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/holdings': {
      id: '/app/holdings'
      path: '/holdings'
      fullPath: '/app/holdings'
      preLoaderRoute: typeof AppHoldingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crypto': {
      id: '/app/crypto'
      path: '/crypto'
      fullPath: '/app/crypto'
      preLoaderRoute: typeof AppCryptoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkout': {
      id: '/app/checkout'
      path: '/checkout'
      fullPath: '/app/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certificates': {
      id: '/app/certificates'
      path: '/certificates'
      fullPath: '/app/certificates'
      preLoaderRoute: typeof AppCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cart': {
      id: '/app/cart'
      path: '/cart'
      fullPath: '/app/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/card': {
      id: '/app/card'
      path: '/card'
      fullPath: '/app/card'
      preLoaderRoute: typeof AppCardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buy': {
      id: '/app/buy'
      path: '/buy'
      fullPath: '/app/buy'
      preLoaderRoute: typeof AppBuyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/waitlist': {
      id: '/admin/waitlist'
      path: '/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AdminWaitlistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vaults': {
      id: '/admin/vaults'
      path: '/vaults'
      fullPath: '/admin/vaults'
      preLoaderRoute: typeof AdminVaultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-health': {
      id: '/admin/system-health'
      path: '/system-health'
      fullPath: '/admin/system-health'
      preLoaderRoute: typeof AdminSystemHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seed-exports': {
      id: '/admin/seed-exports'
      path: '/seed-exports'
      fullPath: '/admin/seed-exports'
      preLoaderRoute: typeof AdminSeedExportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketplace': {
      id: '/admin/marketplace'
      path: '/marketplace'
      fullPath: '/admin/marketplace'
      preLoaderRoute: typeof AdminMarketplaceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jewelry-orders': {
      id: '/admin/jewelry-orders'
      path: '/jewelry-orders'
      fullPath: '/admin/jewelry-orders'
      preLoaderRoute: typeof AdminJewelryOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crypto': {
      id: '/admin/crypto'
      path: '/crypto'
      fullPath: '/admin/crypto'
      preLoaderRoute: typeof AdminCryptoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/couriers': {
      id: '/admin/couriers'
      path: '/couriers'
      fullPath: '/admin/couriers'
      preLoaderRoute: typeof AdminCouriersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configs': {
      id: '/admin/configs'
      path: '/configs'
      fullPath: '/admin/configs'
      preLoaderRoute: typeof AdminConfigsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config-versions': {
      id: '/admin/config-versions'
      path: '/config-versions'
      fullPath: '/admin/config-versions'
      preLoaderRoute: typeof AdminConfigVersionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config-backups': {
      id: '/admin/config-backups'
      path: '/config-backups'
      fullPath: '/admin/config-backups'
      preLoaderRoute: typeof AdminConfigBackupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audits': {
      id: '/admin/audits'
      path: '/audits'
      fullPath: '/admin/audits'
      preLoaderRoute: typeof AdminAuditsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/marketplace/': {
      id: '/app/marketplace/'
      path: '/marketplace'
      fullPath: '/app/marketplace/'
      preLoaderRoute: typeof AppMarketplaceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketplace/$slug': {
      id: '/app/marketplace/$slug'
      path: '/marketplace/$slug'
      fullPath: '/app/marketplace/$slug'
      preLoaderRoute: typeof AppMarketplaceSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jewelry-orders/$id': {
      id: '/app/jewelry-orders/$id'
      path: '/$id'
      fullPath: '/app/jewelry-orders/$id'
      preLoaderRoute: typeof AppJewelryOrdersIdRouteImport
      parentRoute: typeof AppJewelryOrdersRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditsRoute: typeof AdminAuditsRoute
  AdminConfigBackupsRoute: typeof AdminConfigBackupsRoute
  AdminConfigVersionsRoute: typeof AdminConfigVersionsRoute
  AdminConfigsRoute: typeof AdminConfigsRoute
  AdminCouriersRoute: typeof AdminCouriersRoute
  AdminCryptoRoute: typeof AdminCryptoRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminJewelryOrdersRoute: typeof AdminJewelryOrdersRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminMarketplaceRoute: typeof AdminMarketplaceRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  AdminSeedExportsRoute: typeof AdminSeedExportsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminSystemHealthRoute: typeof AdminSystemHealthRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVaultsRoute: typeof AdminVaultsRoute
  AdminWaitlistRoute: typeof AdminWaitlistRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditsRoute: AdminAuditsRoute,
  AdminConfigBackupsRoute: AdminConfigBackupsRoute,
  AdminConfigVersionsRoute: AdminConfigVersionsRoute,
  AdminConfigsRoute: AdminConfigsRoute,
  AdminCouriersRoute: AdminCouriersRoute,
  AdminCryptoRoute: AdminCryptoRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminJewelryOrdersRoute: AdminJewelryOrdersRoute,
  AdminKycRoute: AdminKycRoute,
  AdminMarketplaceRoute: AdminMarketplaceRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  AdminSeedExportsRoute: AdminSeedExportsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminSystemHealthRoute: AdminSystemHealthRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVaultsRoute: AdminVaultsRoute,
  AdminWaitlistRoute: AdminWaitlistRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppJewelryOrdersRouteChildren {
  AppJewelryOrdersIdRoute: typeof AppJewelryOrdersIdRoute
}

const AppJewelryOrdersRouteChildren: AppJewelryOrdersRouteChildren = {
  AppJewelryOrdersIdRoute: AppJewelryOrdersIdRoute,
}

const AppJewelryOrdersRouteWithChildren =
  AppJewelryOrdersRoute._addFileChildren(AppJewelryOrdersRouteChildren)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppBuyRoute: typeof AppBuyRoute
  AppCardRoute: typeof AppCardRoute
  AppCartRoute: typeof AppCartRoute
  AppCertificatesRoute: typeof AppCertificatesRoute
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppCryptoRoute: typeof AppCryptoRoute
  AppHoldingsRoute: typeof AppHoldingsRoute
  AppInvestRoute: typeof AppInvestRoute
  AppJewelryOrdersRoute: typeof AppJewelryOrdersRouteWithChildren
  AppKycRoute: typeof AppKycRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSupportRoute: typeof AppSupportRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMarketplaceSlugRoute: typeof AppMarketplaceSlugRoute
  AppMarketplaceIndexRoute: typeof AppMarketplaceIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppBuyRoute: AppBuyRoute,
  AppCardRoute: AppCardRoute,
  AppCartRoute: AppCartRoute,
  AppCertificatesRoute: AppCertificatesRoute,
  AppCheckoutRoute: AppCheckoutRoute,
  AppCryptoRoute: AppCryptoRoute,
  AppHoldingsRoute: AppHoldingsRoute,
  AppInvestRoute: AppInvestRoute,
  AppJewelryOrdersRoute: AppJewelryOrdersRouteWithChildren,
  AppKycRoute: AppKycRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppProfileRoute: AppProfileRoute,
  AppSupportRoute: AppSupportRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
  AppMarketplaceSlugRoute: AppMarketplaceSlugRoute,
  AppMarketplaceIndexRoute: AppMarketplaceIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AmlComplianceRoute: AmlComplianceRoute,
  AmlPolicyRoute: AmlPolicyRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  BuyRoute: BuyRoute,
  ContactRoute: ContactRoute,
  InsuranceRoute: InsuranceRoute,
  InvestRoute: InvestRoute,
  JewelryRoute: JewelryRoute,
  PrivacyRoute: PrivacyRoute,
  ProofOfReservesRoute: ProofOfReservesRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
